name: "image-resizer"

services:

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /Users/sfe34/oliviazuo-portfolio:/mnt/gcsfuse


volumes:
  bucket:
