[package]
name = "service"
version = "0.0.5"
edition = "2021"
default-run = "service"
authors.workspace = true

[dependencies]
image = { version = "0.25.4" , features = ["rayon"]}
fast_image_resize = { version = "5.0.0", features = ["rayon", "image"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.12"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
rand = "0.8"
hyper-util = { version = "0.1.9", features = ["full"] }
log = "0.4"
log4rs = "1.3"
futures = "0.3.31"
futures-util = "0.3.31"
rayon = "1.10.0"
