name: Push Registry

on:
  push:
    branches: [ "dev" ]

env:
  REGION: europe-west2
  PROJECT: listen-and-learn-411214
  REPO_DEV: image-resizer-dev
  IMAGE: image-resizer:latest

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set vars
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE" >> $GITHUB_ENV

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GC_IMAGE_MANAGER_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}