name: Service CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always
  REGION: europe-west2
  PROJECT: listen-and-learn-411214
  REPO_DEV: image-resizer-dev
  IMAGE: image-resizer

jobs:
  rust-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Check
        run: cargo check --workspace

      - name: Run tests
        run: cargo test --package service

  docker-image-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set vars
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO_DEV/$IMAGE" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./service/Dockerfile
          push: false
          tags: ${{ env.IMAGE_TAG }}